site_name: FIFTH | An x86 FORTH
nav:
  - Home: index.md
  - About: about.md
  - License: license.md
  - Reference:
    - reference.md
    - Stack Manipulation: reference/stack.md
    - Arithmetic: reference/arithmetic.md
    - Notation: reference/notation.md
markdown_extensions:
  - superscript
